In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr) # Output: [1 2 3 4 5]

[1 2 3 4 5]


In [ ]:
#Matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
zeros = np.zeros((2, 3)) # 2x3 matrix of zeros
ones = np.ones((3, 3)) # 3x3 matrix of ones
rand = np.random.rand(3, 3) # 3x3 matrix with random values
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape) # (2, 3) -> Rows x Columns
print(arr.size) # 6 -> Total number of elements
print(arr.ndim) # 2 -> Number of dimensions
print(arr.dtype) # int64 -> Data type

(2, 3)
6
2
int64


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0]) # 10 (First element)
print(arr[-1]) # 50 (Last element)

10
50


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0]) # 10 (First element)
print(arr[-1]) # 50 (Last element)

10
50


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0]) # 10 (First element)
print(arr[-1]) # 50 (Last element)

10
50


In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix[1, 2]) # 6 (Row 1, Column 2)

6


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4]) # [20 30 40]
print(arr[:3]) # [10 20 30]
print(arr[-3:]) # [30 40 50]

[20 30 40]
[10 20 30]
[30 40 50]


Mathematical Operations:

a. Element-wise Operations


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b) # [5 7 9]
print(a * b) # [4 10 18]
print(a ** 2) # [1 4 9]

[5 7 9]
[ 4 10 18]
[1 4 9]


b. Aggregate Functions

In [ ]:
arr = np.array([10, 20, 30, 40])
print(arr.sum()) # 100
print(arr.mean()) # 25.0
print(arr.max()) # 40
print(arr.min()) # 10
print(arr.std()) # Standard deviation

100
25.0
40
10
11.180339887498949


Reshaping & Transposing

a. Reshape an Array

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3)) # 2 rows, 3 columns
print(reshaped)

[[1 2 3]
 [4 5 6]]


b. Transpose a Matrix

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix.T)

[[1 4]
 [2 5]
 [3 6]]


Stacking & Splitting in Array:

a. Stacking Array(Combining)

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.hstack((a, b))) # Horizontal stack
print(np.vstack((a, b))) # Vertical stack

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


b.Splitting Array

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.split(arr, 2)) # Split into 2 parts

[array([1, 2, 3]), array([4, 5, 6])]


Boolean Indexing & Filtering

a. Boolean Masking

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 25]) # [30 40 50]

[30 40 50]


b. Where Condition

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(np.where(arr % 2 == 0, "Even", "Odd")) #(a>b)? T:F
# ['Odd' 'Even' 'Odd' 'Even' 'Odd']

['Odd' 'Even' 'Odd' 'Even' 'Odd']


Linear Algebra with NumPy:

a. Dot Product

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b)) # Matrix multiplication

[[19 22]
 [43 50]]


b. Determinant of a Matrix

In [ ]:
matrix = np.array([[1, 2], [3, 4]])
print(np.linalg.det(matrix))

-2.0000000000000004


c. Eigenvalues & Eigenvectors

In [ ]:
matrix = np.array([[2, 3], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)
print(eigenvectors)

[-0.16227766  6.16227766]
[[-0.81124219 -0.58471028]
 [ 0.58471028 -0.81124219]]


a.Sum and load NumPy Arrays

In [ ]:
np.save('array.npy', arr) # Save
loaded_arr = np.load('array.npy') # Load
print(loaded_arr)


[1 2 3 4 5]


NumPy Array vs Pyhton List

In [ ]:
import numpy as np
import time
size = 10**6
# Python List
python_list = list(range(size))
start = time.time()
python_result = [x * 2 for x in python_list]
end = time.time()
print(f"Python List Time: {end - start:.5f} sec")
# NumPy Array
numpy_array = np.arange(size)
start = time.time()
numpy_result = numpy_array * 2
end = time.time()
print(f"NumPy Array Time: {end - start:.5f} sec")

Python List Time: 0.13109 sec
NumPy Array Time: 0.00569 sec


Pandas:

In [ ]:
import pandas as pd
import numpy as np
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
pd.Series(np.random.randn(5))

0    1.127211
1    0.221314
2    2.348943
3    0.971433
4    1.024508
dtype: float64

In [ ]:
d = {"b": 1, "a": 0, "c": 2}
pd.Series(d)

b    1
a    0
c    2
dtype: int64

In [ ]:
pd.Series(d, index=["b", "c", "d", "a"])

b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64

In [ ]:
s.iloc[0]

np.float64(-0.9412468596108504)

In [ ]:
s.iloc[:3]

a   -0.941247
b   -0.516847
c   -0.641425
dtype: float64

In [ ]:
s[s > s.median()]

b   -0.516847
e    0.134410
dtype: float64

In [ ]:
s.iloc[[4, 3, 1]]

e    0.134410
d   -0.940794
b   -0.516847
dtype: float64

Data Frame

In [ ]:
d = {
"one": pd.Series([1.0, 2.0, 3.0], index=["a", "b", "c"]),
"two": pd.Series([1.0, 2.0, 3.0, 4.0], index=["a", "b", "c", "d"]),
}
df = pd.DataFrame(d)
df

one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [ ]:
pd.DataFrame(d, index=["d", "b", "a"])

one  two
d  NaN  4.0
b  2.0  2.0
a  1.0  1.0

In [ ]:
pd.DataFrame(d, index=["d", "b", "a"], columns=["two", "three"])
# three nor speified therefore NaN is displayed, Not An Number

two three
d  4.0   NaN
b  2.0   NaN
a  1.0   NaN

In [ ]:
df.index
df.columns

Index(['one', 'two'], dtype='object')

In [ ]:
d = {"one": [1.0, 2.0, 3.0, 4.0], "two": [4.0, 3.0, 2.0, 1.0]}
pd.DataFrame(d)

one  two
0  1.0  4.0
1  2.0  3.0
2  3.0  2.0
3  4.0  1.0

In [ ]:
pd.DataFrame(
{
("a", "b"): {("A", "B"): 1, ("A", "C"): 2},("a", "a"): {("A", "C"): 3, ("A", "B"): 4},
("a", "c"): {("A", "B"): 5, ("A", "C"): 6},
("b", "a"): {("A", "C"): 7, ("A", "B"): 8},
("b", "b"): {("A", "D"): 9, ("A", "B"): 10},
}
)

a              b      
       b    a    c    a     b
A B  1.0  4.0  5.0  8.0  10.0
  C  2.0  3.0  6.0  7.0   NaN
  D  NaN  NaN  NaN  NaN   9.0